Add itertools-ts to TypeScript and JavaScript sections
MunGell/awesome-for-beginners pull request #1395
Opened 2024-03-03 21:46 UTC by Smoren

# [itertools-ts](https://github.com/Smoren/itertools-ts) · [![npm](https://img.shields.io/npm/v/itertools-ts.svg)](https://www.npmjs.com/package/itertools-ts) [![Coverage Status](https://coveralls.io/repos/github/Smoren/itertools-ts/badge.svg?branch=master&rand=123)](https://coveralls.io/github/Smoren/itertools-ts?branch=master) ![Build and test](https://github.com/Smoren/itertools-ts/actions/workflows/test_master.yml/badge.svg)

Extended itertools port for TypeScript and JavaScript. Provides a huge set of functions for working with iterable collections (including async ones).

**Loop Iteration Tools Example**

```typescript
import { multi } from 'itertools-ts';

for (const [letter, number] of multi.zip(['a', 'b'], [1, 2])) {
  console.log(`${letter}${number}`);  // a1, b2
}

// Async example
for await (const [letter, number] of multi.zipAsync(['a', 'b'].map((x) => Promise.resolve(x)), [1, 2].map((x) => Promise.resolve(x)))) {
  console.log(`${letter}${number}`);  // a1, b2
}
```

**Stream Iteration Tools Example**

```typescript
import { Stream, AsyncStream } from 'itertools-ts';

const result1 = Stream.of([1, 1, 2, 2, 3, 4, 5])
  .distinct()             // [1, 2, 3, 4, 5]
  .map((x) => x**2)       // [1, 4, 9, 16, 25]
  .filter((x) => x < 10)  // [1, 4, 9]
  .toSum();               // 14

// Async example
const result2 = await AsyncStream.of([1, 1, 2, 2, 3, 4, 5].map((x) => Promise.resolve(x)))
  .distinct()             // [1, 2, 3, 4, 5]
  .map((x) => x**2)       // [1, 4, 9, 16, 25]
  .filter((x) => x < 10)  // [1, 4, 9]
  .toSum();               // 14
```

All functions work on iterable collections and iterators:
* `Array`
* `Set`
* `Map`
* `String`
* `Generator`
* `Iterable`
* `Iterator`

Every function have an analog with "Async"-suffixed name for working with async iterable and iterators (e.g. `zip` and `zipAsync`):
* `AsyncIterable`
* `AsyncIterator`

If an asynchronous function takes other functions as input, they can also be asynchronous.

## Stream and Async Stream
Streams provide a fluent interface to transform arrays and iterables (sync or async) through a pipeline of operations.

Streams are made up of:

1. One stream source factory method to create the stream.
2. Zero or more stream operators that transform the stream to a new stream.
3. Terminal operation of either:
   * Stream terminal operation to transform the stream to a value or data structure.
     ```typescript
     const result1 = Stream.of([1, 1, 2, 2, 3, 4, 5])
       .distinct()             // [1, 2, 3, 4, 5]
       .map((x) => x**2)       // [1, 4, 9, 16, 25]
       .filter((x) => x < 10)  // [1, 4, 9]
       .toSum();               // 14

     // Async example
     const result2 = await AsyncStream.of([1, 1, 2, 2, 3, 4, 5].map((x) => Promise.resolve(x)))
       .distinct()             // [1, 2, 3, 4, 5]
       .map((x) => x**2)       // [1, 4, 9, 16, 25]
       .filter((x) => x < 10)  // [1, 4, 9]
       .toSum();               // 14
     ```
   * The stream is iterated via a `for` loop.
     ```typescript
     const result1 = Stream.of([1, 1, 2, 2, 3, 4, 5])
       .distinct()             // [1, 2, 3, 4, 5]
       .map((x) => x**2)       // [1, 4, 9, 16, 25]
       .filter((x) => x < 10); // [1, 4, 9]

     for (const item of result1) {
       // 1, 4, 9
     }

     // Async example
     const result2 = AsyncStream.of([1, 1, 2, 2, 3, 4, 5].map((x) => Promise.resolve(x)))
       .distinct()             // [1, 2, 3, 4, 5]
       .map((x) => x**2)       // [1, 4, 9, 16, 25]
       .filter((x) => x < 10); // [1, 4, 9]

     for await (const item of result2) {
       // 1, 4, 9
     }
     ```

2024-05-14 15:22 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2024-10-19 14:28 UTC, sammyhori reviewed
Repo is mostly inactive, one update 3 weeks ago but only a few commits this year.

2024-10-19 21:44 UTC, sammyhori commented
Going to close this for now due to worries about inactivity, feel free to reopen this if the repo becomes more active

2025-01-25 20:40 UTC, Smoren commented
@sammyhori Please reopen my PR because the repo is more active now. Thanks!

2025-01-28 21:28 UTC, sammyhori requested changes
Thanks for the contribution.
This pull request looks okay to me, there is only 1 beginner friendly issue and the repo has become slightly activate again recently - through the owner of the repo (and this pull request).

I have requested a change, feel free to commit it or discuss it with me if you would like.

2025-01-28 22:21 UTC, Smoren commented
Thank you @sammyhori for your feedback! I've commited you change request.

There is indeed only one issue in the project right now, but it includes many tasks for implementing various functions, and it will be updated over time. 

I also have plans to add several useful functions to the set category myself in the near future, so the repository will remain active.

2025-02-06 21:53 UTC, Dianne087 commented
i am good guy so i will help github

2025-02-06 21:54 UTC, Dianne087 commented
so all merge

2025-02-07 19:34 UTC, sammyhori approved these changes
Looks Good To Me!

Thanks for the changes and explanation.

May I recommend, if you want an issue tracking features, you could also have separate issues for each feature and link to each feature  issue (using #...) in your tracking issue (see #1449 for a similar example).

This approach can facilitate tracking which features have been implemented and which have not, while also providing greater flexibility in utilising some of GitHub's functionalities, such as linking pull requests to issues for automatic closure upon merging the pull request.

Sammy :)

2025-02-07 19:34 UTC, merged

2025-02-09 12:48 UTC, Smoren commented
@sammyhori Thank you for merging my PR and for your suggestion. It is a really good idea. I did it [here](https://github.com/Smoren/itertools-ts/issues/50) :)