add Rawsec Cybersecurity Inventory
MunGell/awesome-for-beginners pull request #1506
Opened 2024-10-31 21:32 UTC by noraj

related to #1127

2024-11-03 21:01 UTC, sammyhori requested changes
Hi @noraj, thank you for the contribution!

I'm happy to merge this PR once the minor formatting fix is committed.

The repo is large and the last commit was 2 days ago. My only worry is that that the number of beginner level issues is 3 in 80, with only one of them opened in the last 2 years.

One to keep an eye on... but happy to add for now.

2024-11-03 23:07 UTC, noraj commented
> The repo is large and the last commit was 2 days ago. My only worry is that that the number of beginner level issues is 3 in 80, with only one of them opened in the last 2 years.

In fact I wanted to add multiple labels: difficulty::easy, hacktoberfest, type::new content. But it seems the syntax allows only 1 label. Maybe I could just manually batch tag them.

2024-11-03 23:08 UTC, noraj commented on data.json
> +        },
true that JS doesn't care about trailing comma but JSON does.

2024-11-04 19:35 UTC, sammyhori approved these changes

2024-11-04 19:36 UTC, sammyhori commented
LGTM now :), thanks a lot for the work you'e put into this entry.

2024-11-04 19:36 UTC, merged